### ISSUE TITLE
Tailwind Custom Color Theme

### ISSUE THREAD

**Issue by Bojken07** [Bojken07/Projekt_Backend#6]
User Story

As a develoer, i want to implement a cohesive color pallete to create a visually appealing homepage and simlify consistent styling across the application.
https://github.com/Bojken07/DigitalStock/issues/4

###TODO

- [x] Create our own Company Color Theme

- [x] Research customization of tailwind CSS classes (Colors mainly)

- [x] Implement color theme into application

Documentation: [Source](https://tailwindcss.com/docs/customizing-colors)

- [ ]
